version: '3.4'

services:
  migration:
    image: orbisk/primebot
    depends_on:
      mariadb:
        condition: service_healthy
      mongodb:
        condition: service_healthy
    environment:
      - MONGODB_USERNAME
      - MONGODB_PASSWORD
      - MONGODB_HOST
      - MONGODB_PORT
      - DB_NAME
      - DB_USER
      - DB_PASSWORD
      - DB_HOST
      - DB_PORT
      - TELEGRAM_BOT_API_KEY
      - DISCORD_API_KEY
      - DISCORD_APP_CLIENT_ID
      - DJANGO_SECRET_KEY
      - DJANGO_DEBUG
      - DJANGO_ALLOWED_HOSTS
      - SITE_ID
      - STATIC_ROOT
      - MEDIA_ROOT
      - LOGGING_DIR
      - FERNET_SECRET_KEY
      - TG_DEVELOPER_GROUP
      - FILES_FROM_STORAGE
      - GIT_TOKEN
      - GAME_SPORTS_BASE_URL
    command: [ 'python', 'manage.py', 'migrate' ]

  app:
    networks:
      - proxy
      - default
    depends_on:
      - migration
    expose:
      - 8000
    image: orbisk/primebot
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.entrypoints=websecure,web"
      - "traefik.http.routers.app.rule=Host(`primebot.me`)"
      - "traefik.http.services.app.loadbalancer.server.port=8000"
      - "traefik.http.routers.app.tls=true"
      - "traefik.http.routers.app.tls.certResolver=production"
    environment:
      - MONGODB_USERNAME
      - MONGODB_PASSWORD
      - MONGODB_HOST
      - MONGODB_PORT
      - DB_NAME
      - DB_USER
      - DB_PASSWORD
      - DB_HOST
      - DB_PORT
      - TELEGRAM_BOT_API_KEY
      - DISCORD_API_KEY
      - DISCORD_APP_CLIENT_ID
      - DJANGO_SECRET_KEY
      - DJANGO_DEBUG
      - DJANGO_ALLOWED_HOSTS
      - SITE_ID
      - STATIC_ROOT
      - MEDIA_ROOT
      - LOGGING_DIR
      - FERNET_SECRET_KEY
      - TG_DEVELOPER_GROUP
      - FILES_FROM_STORAGE
      - GIT_TOKEN
      - GAME_SPORTS_BASE_URL
    restart: unless-stopped
    volumes:
      - media:/var/opt/prime_bot_backend/media/
    command: [ "gunicorn", "-b", ":8000", "--workers=3", "primebot_backend.wsgi:application" ]

  mongodb:
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGODB_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGODB_PASSWORD
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: [ "CMD","mongosh", "--eval", "db.adminCommand('ping')" ]

  queue-cluster:
    image: orbisk/primebot
    depends_on:
      - migration
    restart: unless-stopped
    environment:
      - MONGODB_USERNAME
      - MONGODB_PASSWORD
      - MONGODB_HOST
      - MONGODB_PORT
      - DB_NAME
      - DB_USER
      - DB_PASSWORD
      - DB_HOST
      - DB_PORT
      - TELEGRAM_BOT_API_KEY
      - DISCORD_API_KEY
      - DISCORD_APP_CLIENT_ID
      - DJANGO_SECRET_KEY
      - DJANGO_DEBUG
      - DJANGO_ALLOWED_HOSTS
      - SITE_ID
      - STATIC_ROOT
      - MEDIA_ROOT
      - LOGGING_DIR
      - FERNET_SECRET_KEY
      - TG_DEVELOPER_GROUP
      - FILES_FROM_STORAGE
      - GIT_TOKEN
      - GAME_SPORTS_BASE_URL
    command: [ 'python', 'manage.py', 'qcluster' ]

  discord-bot:
    depends_on:
      - migration
    image: orbisk/primebot
    restart: unless-stopped
    command: [ 'python', 'manage.py', 'discord_bot' ]
    environment:
      - MONGODB_USERNAME
      - MONGODB_PASSWORD
      - MONGODB_HOST
      - MONGODB_PORT
      - DB_NAME
      - DB_USER
      - DB_PASSWORD
      - DB_HOST
      - DB_PORT
      - TELEGRAM_BOT_API_KEY
      - DISCORD_API_KEY
      - DISCORD_APP_CLIENT_ID
      - DJANGO_SECRET_KEY
      - DJANGO_DEBUG
      - DJANGO_ALLOWED_HOSTS
      - SITE_ID
      - STATIC_ROOT
      - MEDIA_ROOT
      - LOGGING_DIR
      - FERNET_SECRET_KEY
      - TG_DEVELOPER_GROUP
      - FILES_FROM_STORAGE
      - GIT_TOKEN
      - GAME_SPORTS_BASE_URL

  telegram-bot:
    image: orbisk/primebot
    depends_on:
      - migration
    restart: unless-stopped
    command: [ 'python', 'manage.py', 'telegram_bot' ]
    environment:
      - MONGODB_USERNAME
      - MONGODB_PASSWORD
      - MONGODB_HOST
      - MONGODB_PORT
      - DB_NAME
      - DB_USER
      - DB_PASSWORD
      - DB_HOST
      - DB_PORT
      - TELEGRAM_BOT_API_KEY
      - DISCORD_API_KEY
      - DISCORD_APP_CLIENT_ID
      - DJANGO_SECRET_KEY
      - DJANGO_DEBUG
      - DJANGO_ALLOWED_HOSTS
      - SITE_ID
      - STATIC_ROOT
      - MEDIA_ROOT
      - LOGGING_DIR
      - FERNET_SECRET_KEY
      - TG_DEVELOPER_GROUP
      - FILES_FROM_STORAGE
      - GIT_TOKEN
      - GAME_SPORTS_BASE_URL

  mariadb:
    image: mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
      MARIADB_MYSQL_LOCALHOST_USER: true
    volumes:
      - database:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "healthcheck.sh" ,"--su-mysql", "--connect", "--innodb_initialized" ]

  caddy:
    image: orbisk/primebot-fileserver
    command: ["caddy","file-server", "--root", "/www/html", "--listen", "0.0.0.0:80"]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.caddy.entrypoints=websecure,web"
      - "traefik.http.routers.caddy.rule=(Host(`primebot.me`) && Path(`/static`))"
      - "traefik.http.middlewares.caddy-stripprefix.stripprefix.prefixes=/static"
      - "traefik.http.routers.caddy.middlewares=caddy-stripprefix@docker"
      - "traefik.http.services.caddy.loadbalancer.server.port=80"
      - "traefik.http.routers.caddy.tls=true"
      - "traefik.http.routers.caddy.tls.certResolver=production"
    networks:
      - default
      - proxy

  memcached:
    image: memcached
    restart: unless-stopped

volumes:
  database:
  mongo-data:
  media:

networks:
  proxy:
    external: true
