version: '3.4'

# Development only
# For production see https://github.com/random-rip/primebot-deployment/blob/main/docker-compose.yml

services:
  app:
    networks:
      - proxy
    depends_on:
      - mariadb
      - mongodb
    image: orbisk/primebot
    environment:
      - MONGODB_USERNAME
      - MONGODB_PASSWORD
      - MONGODB_HOST
      - MONGODB_PORT
      - DB_NAME
      - DB_USER
      - DB_PASSWORD
      - DB_HOST
      - DB_PORT
      - TELEGRAM_BOT_API_KEY
      - DISCORD_API_KEY
      - DISCORD_APP_CLIENT_ID
      - DJANGO_SECRET_KEY
      - DJANGO_DEBUG
      - DJANGO_ALLOWED_HOSTS
      - SITE_ID
      - STATIC_ROOT
      - MEDIA_ROOT
      - LOGGING_DIR
      - FERNET_SECRET_KEY
      - TG_DEVELOPER_GROUP
      - FILES_FROM_STORAGE
      - GIT_TOKEN
      - GAME_SPORTS_BASE_URL
    volumes:
      - .:/app
    restart: unless-stopped

  mongodb:
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGODB_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGODB_PASSWORD
    volumes:
      - mongo-data:/data/db

  queue-cluster:
    image: orbisk/primebot
    restart: unless-stopped
    environment:
      - MONGODB_USERNAME
      - MONGODB_PASSWORD
      - MONGODB_HOST
      - MONGODB_PORT
      - DB_NAME
      - DB_USER
      - DB_PASSWORD
      - DB_HOST
      - DB_PORT
      - TELEGRAM_BOT_API_KEY
      - DISCORD_API_KEY
      - DISCORD_APP_CLIENT_ID
      - DJANGO_SECRET_KEY
      - DJANGO_DEBUG
      - DJANGO_ALLOWED_HOSTS
      - SITE_ID
      - STATIC_ROOT
      - MEDIA_ROOT
      - LOGGING_DIR
      - FERNET_SECRET_KEY
      - TG_DEVELOPER_GROUP
      - FILES_FROM_STORAGE
      - GIT_TOKEN
      - GAME_SPORTS_BASE_URL
    command: ['python', 'manage.py', 'qcluster' ]

  discord-bot:
    image: orbisk/primebot
    restart: unless-stopped
    command: ['python', 'manage.py', 'discord_bot' ]
    environment:
      - MONGODB_USERNAME
      - MONGODB_PASSWORD
      - MONGODB_HOST
      - MONGODB_PORT
      - DB_NAME
      - DB_USER
      - DB_PASSWORD
      - DB_HOST
      - DB_PORT
      - TELEGRAM_BOT_API_KEY
      - DISCORD_API_KEY
      - DISCORD_APP_CLIENT_ID
      - DJANGO_SECRET_KEY
      - DJANGO_DEBUG
      - DJANGO_ALLOWED_HOSTS
      - SITE_ID
      - STATIC_ROOT
      - MEDIA_ROOT
      - LOGGING_DIR
      - FERNET_SECRET_KEY
      - TG_DEVELOPER_GROUP
      - FILES_FROM_STORAGE
      - GIT_TOKEN
      - GAME_SPORTS_BASE_URL

  telegram-bot:
    image: orbisk/primebot
    restart: unless-stopped
    command: ['python', 'manage.py', 'telegram_bot' ]
    environment:
      - MONGODB_USERNAME
      - MONGODB_PASSWORD
      - MONGODB_HOST
      - MONGODB_PORT
      - DB_NAME
      - DB_USER
      - DB_PASSWORD
      - DB_HOST
      - DB_PORT
      - TELEGRAM_BOT_API_KEY
      - DISCORD_API_KEY
      - DISCORD_APP_CLIENT_ID
      - DJANGO_SECRET_KEY
      - DJANGO_DEBUG
      - DJANGO_ALLOWED_HOSTS
      - SITE_ID
      - STATIC_ROOT
      - MEDIA_ROOT
      - LOGGING_DIR
      - FERNET_SECRET_KEY
      - TG_DEVELOPER_GROUP
      - FILES_FROM_STORAGE
      - GIT_TOKEN
      - GAME_SPORTS_BASE_URL

  mariadb:
    image: mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
    volumes:
      - database:/var/lib/mysql

volumes:
  database:
  mongo-data:

networks:
  proxy:
    external: true
