name: Deploy

on:
  push:
    tags:
      - v*



jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME  }}
          password: ${{ secrets.DOCKERHUB_TOKEN  }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: orbisk/primebot:latest,orbisk/primebot:${{github.ref_name}}
          context: .
          target: base
          file: Dockerfile

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: orbisk/primebot-fileserver:latest,orbisk/primebot-fileserver:${{github.ref_name}}
          context: .
          target: fileserver
          file: Dockerfile
